---
version: '3'

services:
  telegram:
    container_name: telegram
    build: 
      context: .
      dockerfile: Dockerfile 
    restart: always
    networks:  
      outside-network:
networks:
  outside-network:
    external:
      name: outside-network
